version: 0.2
phases:
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install
# Include only the files required for your application to run.
artifacts:
  files:
    - server.js
    - node_modules/**/*
